[2023-06-11T15:25:46.313+0000] {taskinstance.py:1097} INFO - Dependencies not met for <TaskInstance: dag_cron_expression_03.task1 scheduled__2022-11-02T03:00:00+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2023-06-11T15:25:46.313294+00:00 and task will be retried at 2023-06-11T15:29:50.863522+00:00.
[2023-06-11T15:25:46.564+0000] {local_task_job_runner.py:154} INFO - Task is not able to be run
[2023-06-11T15:30:00.532+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cron_expression_03.task1 scheduled__2022-11-02T03:00:00+00:00 [queued]>
[2023-06-11T15:30:00.879+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cron_expression_03.task1 scheduled__2022-11-02T03:00:00+00:00 [queued]>
[2023-06-11T15:30:00.879+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 6
[2023-06-11T15:30:01.489+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): task1> on 2022-11-02 03:00:00+00:00
[2023-06-11T15:30:01.553+0000] {standard_task_runner.py:57} INFO - Started process 871 to run task
[2023-06-11T15:30:01.583+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_cron_expression_03', 'task1', 'scheduled__2022-11-02T03:00:00+00:00', '--job-id', '1349', '--raw', '--subdir', 'DAGS_FOLDER/dag_cron.py', '--cfg-path', '/tmp/tmpc9d1_cj4']
[2023-06-11T15:30:01.623+0000] {standard_task_runner.py:85} INFO - Job 1349: Subtask task1
[2023-06-11T15:30:01.997+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_cron_expression_03.task1 scheduled__2022-11-02T03:00:00+00:00 [running]> on host 7586ce0070ac
[2023-06-11T15:30:05.132+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Raja' AIRFLOW_CTX_DAG_ID='dag_cron_expression_03' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2022-11-02T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-11-02T03:00:00+00:00'
[2023-06-11T15:30:05.149+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-11T15:30:05.183+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo dag with cron expression!']
[2023-06-11T15:30:05.611+0000] {subprocess.py:86} INFO - Output:
[2023-06-11T15:30:05.655+0000] {subprocess.py:93} INFO - dag with cron expression!
[2023-06-11T15:30:05.656+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-06-11T15:30:06.159+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=dag_cron_expression_03, task_id=task1, execution_date=20221102T030000, start_date=20230611T153000, end_date=20230611T153006
[2023-06-11T15:30:06.492+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-11T15:30:07.111+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
